import { StyleSheet } from 'react-native';

export const Mapstyles = StyleSheet.create({
  container: {
    flex: 1,
  },
  coordinatesBar: {
    position: 'absolute',
    left: 10,
    right: 10,
    backgroundColor: 'white',
    padding: 10,
    borderRadius: 8,
    zIndex: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 3,
  },
  coordinatesText: {
    fontSize: 14,
    textAlign: 'center',
    fontFamily: 'monospace',
  },
  map: {
    flex: 1,
  },
  marker: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: '#FF6B6B',
    borderWidth: 3,
    borderColor: 'white',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  markerDragging: {
    backgroundColor: '#4CAF50',
    transform: [{ scale: 1.2 }],
    shadowOpacity: 0.4,
    shadowRadius: 6,
    elevation: 8,
  },
  markerWrap: {
    alignItems: 'center',
  },
  markerContainer: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  markerPin: {
    backgroundColor: 'transparent',
    alignItems: 'center',
    justifyContent: 'center',
  },
  markerPinDragging: {
    transform: [{ scale: 1.3 }],
  },
  markerDot: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: '#e74c3c',
    borderWidth: 3,
    borderColor: 'white',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  markerDotDragging: {
    backgroundColor: '#ff6b6b',
    borderWidth: 4,
    shadowOpacity: 0.4,
    shadowRadius: 6,
    elevation: 8,
  },
  centerButton: {
    position: 'absolute',
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    borderRadius: 25,
    width: 50,
    height: 50,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  markerLabel: {
    marginTop: 4,
    backgroundColor: 'rgba(255,255,255,0.9)',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 6,
    maxWidth: 140,
    fontSize: 12,
  },
  markerThumb: {
    width: 36,
    height: 36,
    borderRadius: 6,
    marginTop: 6,
  },
});